### ISSUE TITLE
安装了不能用.vue一直说找不到模块

### ISSUE THREAD

**Issue by lifetin** [dreamback/vue-router-transition#2]
安装成功了, 在package.json中有存在的. 在node_modules中也存在文件夹,只是这个文件夹图标是快捷方式的图标.

然后我在main.js中使用这个就报错.
import RouteTransition from 'vue-route-transition'
Vue.use(RouteTransition)
提示这个模块不存在. 可能是和这个快捷方式图标有关.

**Comment by lifetin** [comment]
我是用cnpm安装的, 然后我卸载了, 重新用npm来安装,提示我要安装
 Missing write access to D:\workspace\vue\quan_h5\node_modules\vue-route-transition
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

然后我执行
npm install ajv@^6.0.0

再重新npm install vue-route-transition --save
发现安装成功了. 然后快捷方式图标也不存在了.

我再重启vue cli 

启动时还是报错


This dependency was not found:
* vue-route-transition in ./src/main.js
To install it, you can run: npm install --save vue-route-transition

**Comment by 499596986** [comment]
安装后也找不到 这个模块。。后来  import RouteTransition from  "../node_modules/vue-route-transition/lib/vue_route_transition.min.js"    这样子就可以用了。。

**Comment by lifetin** [comment]
重新安装, 用了1.0.7的,正常了.

**Comment by lifetin** [comment]
但是使用上,还是有问题哦.
![44](https://user-images.githubusercontent.com/10474968/49776167-e745b780-fd35-11e8-9bd1-5eb6c874d587.png)

**Comment by 499596986** [comment]
按他的基本使用 可以动画切换啊。我试过了。没出现这个问题。 我用的是 1.0.6

**Comment by lifetin** [comment]
App.vue
<template>
  <vue-route-transition id="app">
  </vue-route-transition>
</template>

我把这个  <vue-route-transition id="app">  </vue-route-transition>
加在我当前项目中. 然后这里面能不能嵌入router-view 或是其它的组件呢?

**Comment by 499596986** [comment]
用是可以用的。。 把<router-view></router-view>替换成<vue-route-transition>这个的。要用动画的用这个，一个页面的头部和footer要固定的用作者提供的那个结构。。就是 嵌套路由的都要单独写出来。渲染要跳到 顶层的 <vue-route-transition>这个上了。。。有疑问的是 嵌套路由 是不是一定要单独写出来,单独写出来感觉路由不好看
