### ISSUE TITLE
使用过程中出现这种问题

### ISSUE THREAD

**Issue by auven** [dreamback/vue-router-transition#4]
如下，只要我从这样子的链接进入 `http://xx.com` 就会报错，而从 `http://xx.com/#/` 就不会出现这种错误。
![1131545820378_ pic_hd](https://user-images.githubusercontent.com/23731087/50443132-e3708280-093c-11e9-8364-7884091bbb90.jpg)

**Comment by dreamback** [comment]
> 如下，只要我从这样子的链接进入 `http://xx.com` 就会报错，而从 `http://xx.com/#/` 就不会出现这种错误。
> ![1131545820378_ pic_hd](https://user-images.githubusercontent.com/23731087/50443132-e3708280-093c-11e9-8364-7884091bbb90.jpg)

是不是最新版本？最新版本1.1.1

**Comment by auven** [comment]
是最新版的

**Comment by auven** [comment]
我下载你的项目，用项目里的组件就不会，用 `npm` 的包就会
``` js
// 下载你的项目里的组件
import RouteTransition from '@/components/vue-route-transition'
// 使用这个就会出错
// import RouteTransition from 'vue-route-transition'
```
