### ISSUE TITLE
使用插件之后 黏性布局用不了

### ISSUE THREAD

**Issue by Tiramisu1** [dreamback/vue-router-transition#7]
使用没有问题 但是需求首页有黏性布局 这个时候使用插件 黏性布局会失效 即便使用了使用router-layout也不行

**Comment by dreamback** [comment]
是的，transform动画会时fixed会失效。
请参考，demo中的处理。
![image](https://user-images.githubusercontent.com/973402/62183795-1d4fae80-b38e-11e9-823f-eef82fd760d2.png)

**Comment by Tiramisu1** [comment]
dem

> 是的，transform动画会时fixed会失效。
> 请参考，demo中的处理。
> ![image](https://user-images.githubusercontent.com/973402/62183795-1d4fae80-b38e-11e9-823f-eef82fd760d2.png)

你指的demo中的处理是router-layout组件么？ 我使用这个组件之后 黏性布局动画又使用不了
