### ISSUE TITLE
[Vue warn]: Error in data(): "TypeError: Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by veione** [dreamback/vue-router-transition#8]
按照文档配置运行报如下错误：
[Vue warn]: Error in data(): "TypeError: Cannot read property 'length' of null"

found in

---> <VueRouteTransition> at src/components/vue-route-transition/transition.vue
       <App> at src/App.vue
         <Root>

**Comment by 262060984** [comment]
我也遇到这个问题，
好像是如果初始打开的路径不是首页，就会出现这个问题
直接使用https://github.com/dreamback/vue-route-transition/tree/master/src/components/vue-route-transition的源码就能解决…
大概是npm包没有更新？
